spring.kafka.bootstrap-servers=localhost:9092

# enable output with color in the console
spring.output.ansi.enabled=always

# specifies that the ErrorHandlingDeserializer should be used. This deserializer catches and handles deserialization
# errors, preventing the application from crashing.
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# this is the deserializer that will be used to deserialize the messages,
# which means the JsonDeserializer will convert incoming JSON messages to Java objects
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# tells Spring Kafka to deserialize messages into instances of the OrderCreated class by default
spring.kafka.consumer.properties.spring.json.value.default.type=dev.lydtech.dispatch.message.OrderCreated
