spring.application.name=dispatch

# enable color output in the console
spring.output.ansi.enabled=always

# configure the kafka broker server
spring.kafka.bootstrap-servers=localhost:9092

# configure a kafka ErrorHandlingDeserializer to handle deserialization errors
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# configure the kafka deserializer to deserialize the message value as JSON
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# configure the kafka deserializer default value type
spring.kafka.consumer.properties.spring.json.value.default.type=dev.lydtech.dispatch.message.OrderCreated