spring.application.name=dispatch

# enable color output in the console
spring.output.ansi.enabled=always

# configure the kafka broker server
spring.kafka.bootstrap-servers=localhost:9092

# configure the kafka deserializer to deserialize the message value as JSON
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# configure the kafka deserializer default value type
spring.kafka.consumer.properties.spring.json.value.default.type=dev.lydtech.dispatch.message.OrderCreated